spring.application.name=Projekt3_Gruppe_7
spring.datasource.url=jdbc:mysql://localhost:3306/bilabonnement
spring.datasource.username=root
spring.datasource.password=2006
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
spring.sql.init.continue-on-error=false

spring.profiles.active=local

